-- 005_retail_sales.sql

CREATE TABLE IF NOT EXISTS estimate_mast (
    em_ref_no SERIAL PRIMARY KEY,
    em_rec_no INTEGER,
    em_char VARCHAR(10),
    em_inv_no VARCHAR(50),
    cust_name VARCHAR(150),
    city VARCHAR(50), dist VARCHAR(50), state VARCHAR(50), state_code VARCHAR(10),
    ph_no VARCHAR(50), gstin VARCHAR(50),
    staff_code INTEGER,
    est_date TIMESTAMPTZ DEFAULT NOW(),
    em_qty NUMERIC(18,2) DEFAULT 0,
    em_gnd_tot NUMERIC(18,2) DEFAULT 0,
    add_less_exp1 VARCHAR(100),
    add_exp1_amt NUMERIC(18,2) DEFAULT 0,
    add_less_exp2 VARCHAR(100),
    add_exp2_amt NUMERIC(18,2) DEFAULT 0,
    em_rnd_off NUMERIC(18,2) DEFAULT 0,
    em_net_total NUMERIC(18,2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'Pending',
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE estimate_mast ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS estimate_child (
    est_ref_no SERIAL PRIMARY KEY,
    em_ref_no INTEGER REFERENCES estimate_mast(em_ref_no) ON DELETE CASCADE,
    bill_no VARCHAR(50), bill_date TIMESTAMPTZ,
    bar_no VARCHAR(50),
    prcode INTEGER REFERENCES product(ref_no),
    grp_code INTEGER REFERENCES product_group(ref_no),
    qty NUMERIC(18,2) DEFAULT 0,
    rate NUMERIC(18,2) DEFAULT 0,
    disc_perc NUMERIC(18,2) DEFAULT 0,
    disc_amt NUMERIC(18,2) DEFAULT 0,
    net_amt NUMERIC(18,2) DEFAULT 0,
    bar_ref_id INTEGER,
    cr_code INTEGER,
    pc_ref_no INTEGER,
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE estimate_child ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS retail_sale_mast (
    rm_ref_no SERIAL PRIMARY KEY,
    rm_rec_no INTEGER,
    em_ref_no INTEGER REFERENCES estimate_mast(em_ref_no),
    em_bill_no VARCHAR(50),
    reg_code INTEGER DEFAULT 50,
    rm_tax_model VARCHAR(50),
    rev_chrg VARCHAR(10) DEFAULT 'No',
    inv_type VARCHAR(50),
    cust_name VARCHAR(150),
    city VARCHAR(50), dist VARCHAR(50), state VARCHAR(50), state_code VARCHAR(10),
    gstin VARCHAR(50), rm_ph_no VARCHAR(50),
    rm_cr_code INTEGER REFERENCES ledger(ledg_code),
    rm_mode_one VARCHAR(50) DEFAULT 'Cash',
    rm_dr_code_one INTEGER REFERENCES ledger(ledg_code),
    rm_recd_one_amt NUMERIC(18,2) DEFAULT 0,
    rm_dbt_dt_one TIMESTAMPTZ,
    rm_mode_two VARCHAR(50),
    rm_dr_code_two INTEGER,
    rm_recd_two_amt NUMERIC(18,2) DEFAULT 0,
    rm_dbt_dt_two TIMESTAMPTZ,
    rm_bill_char VARCHAR(10),
    rm_bill_ref_no VARCHAR(50),
    rm_bill_date TIMESTAMPTZ,
    rm_dr_narr VARCHAR(500),
    rm_cr_narr VARCHAR(500),
    rm_tot_qty NUMERIC(18,2) DEFAULT 0,
    rm_grd_tot NUMERIC(18,2) DEFAULT 0,
    rm_bf_gst_amt NUMERIC(18,2) DEFAULT 0,
    rm_igst_amt NUMERIC(18,2) DEFAULT 0,
    rm_cgst_amt NUMERIC(18,2) DEFAULT 0,
    rm_sgst_amt NUMERIC(18,2) DEFAULT 0,
    rm_rnd_off NUMERIC(18,2) DEFAULT 0,
    rm_net_total NUMERIC(18,2) DEFAULT 0,
    rm_igst_code INTEGER, rm_cgst_code INTEGER, rm_sgst_code INTEGER, rnd_code INTEGER,
    rm_igst_perc NUMERIC(18,2) DEFAULT 0,
    rm_cgst_perc NUMERIC(18,2) DEFAULT 0,
    rm_sgst_perc NUMERIC(18,2) DEFAULT 0,
    rm_frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE retail_sale_mast ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS retail_sale_child (
    dc_ref_no SERIAL PRIMARY KEY,
    rm_ref_no INTEGER REFERENCES retail_sale_mast(rm_ref_no) ON DELETE CASCADE,
    rm_bill_no VARCHAR(50),
    rm_bill_date TIMESTAMPTZ,
    dc_bar_no VARCHAR(50),
    dc_prcode INTEGER REFERENCES product(ref_no),
    dc_pgrcode INTEGER REFERENCES product_group(ref_no),
    dc_qty NUMERIC(18,2) DEFAULT 0,
    dc_rate NUMERIC(18,2) DEFAULT 0,
    dc_net_tot NUMERIC(18,2) DEFAULT 0,
    dc_igst_perc NUMERIC(18,2) DEFAULT 0,
    dc_igst_amnt NUMERIC(18,2) DEFAULT 0,
    dc_cgst_perc NUMERIC(18,2) DEFAULT 0,
    dc_cgst_amnt NUMERIC(18,2) DEFAULT 0,
    dc_sgst_perc NUMERIC(18,2) DEFAULT 0,
    dc_sgst_amnt NUMERIC(18,2) DEFAULT 0,
    bar_ref_id INTEGER,
    cr_code INTEGER,
    pc_ref_no INTEGER,
    emp_no INTEGER,
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE retail_sale_child ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS retail_sale_ret_mast (
    rr_ref_no SERIAL PRIMARY KEY,
    rr_rec_no INTEGER,
    em_ref_no INTEGER,
    em_bill_no VARCHAR(50),
    reg_code INTEGER DEFAULT 50,
    rr_tax_model VARCHAR(50),
    rev_chrg VARCHAR(10) DEFAULT 'No',
    inv_type VARCHAR(50),
    cust_name VARCHAR(150),
    city VARCHAR(50), dist VARCHAR(50), state VARCHAR(50), state_code VARCHAR(10),
    gstin VARCHAR(50), rr_ph_no VARCHAR(50),
    rr_cr_code INTEGER REFERENCES ledger(ledg_code),
    rr_mode_one VARCHAR(50) DEFAULT 'Cash',
    rr_dr_code_one INTEGER REFERENCES ledger(ledg_code),
    rr_recd_one_amt NUMERIC(18,2) DEFAULT 0,
    rr_dbt_dt_one TIMESTAMPTZ,
    rr_mode_two VARCHAR(50),
    rr_dr_code_two INTEGER,
    rr_recd_two_amt NUMERIC(18,2) DEFAULT 0,
    rr_dbt_dt_two TIMESTAMPTZ,
    rr_bill_char VARCHAR(10),
    rr_bill_ref_no VARCHAR(50),
    rr_bill_date TIMESTAMPTZ,
    rr_dr_narr VARCHAR(500),
    rr_cr_narr VARCHAR(500),
    rr_tot_qty NUMERIC(18,2) DEFAULT 0,
    rr_grd_tot NUMERIC(18,2) DEFAULT 0,
    rr_bf_gst_amt NUMERIC(18,2) DEFAULT 0,
    rr_igst_amt NUMERIC(18,2) DEFAULT 0,
    rr_cgst_amt NUMERIC(18,2) DEFAULT 0,
    rr_sgst_amt NUMERIC(18,2) DEFAULT 0,
    rr_rnd_off NUMERIC(18,2) DEFAULT 0,
    rr_net_total NUMERIC(18,2) DEFAULT 0,
    rr_igst_code INTEGER, rr_cgst_code INTEGER, rr_sgst_code INTEGER, rnd_code INTEGER,
    rr_igst_perc NUMERIC(18,2) DEFAULT 0,
    rr_cgst_perc NUMERIC(18,2) DEFAULT 0,
    rr_sgst_perc NUMERIC(18,2) DEFAULT 0,
    rr_frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE retail_sale_ret_mast ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS retail_sale_ret_child (
    dc_ref_no SERIAL PRIMARY KEY,
    rr_ref_no INTEGER REFERENCES retail_sale_ret_mast(rr_ref_no) ON DELETE CASCADE,
    rr_bill_no VARCHAR(50),
    rr_bill_date TIMESTAMPTZ,
    dc_bar_no VARCHAR(50),
    dc_prcode INTEGER REFERENCES product(ref_no),
    dc_pgrcode INTEGER REFERENCES product_group(ref_no),
    dc_qty NUMERIC(18,2) DEFAULT 0,
    dc_rate NUMERIC(18,2) DEFAULT 0,
    dc_net_tot NUMERIC(18,2) DEFAULT 0,
    dc_igst_perc NUMERIC(18,2) DEFAULT 0,
    dc_igst_amnt NUMERIC(18,2) DEFAULT 0,
    dc_cgst_perc NUMERIC(18,2) DEFAULT 0,
    dc_cgst_amnt NUMERIC(18,2) DEFAULT 0,
    dc_sgst_perc NUMERIC(18,2) DEFAULT 0,
    dc_sgst_amnt NUMERIC(18,2) DEFAULT 0,
    bar_ref_id INTEGER,
    cr_code INTEGER,
    pc_ref_no INTEGER,
    emp_no INTEGER,
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE retail_sale_ret_child ENABLE ROW LEVEL SECURITY;
