-- 006_wholesale.sql

CREATE TABLE IF NOT EXISTS del_chall_mast (
    del_ref_no SERIAL PRIMARY KEY,
    rec_no INTEGER,
    reg_code INTEGER DEFAULT 50,
    tax_model VARCHAR(50),
    dr_code INTEGER REFERENCES ledger(ledg_code),
    cr_code INTEGER REFERENCES ledger(ledg_code),
    bill_char VARCHAR(10),
    bill_ref_no VARCHAR(50),
    bill_date TIMESTAMPTZ,
    tot_qty NUMERIC(18,2) DEFAULT 0,
    grd_tot NUMERIC(18,2) DEFAULT 0,
    add_less_exp1 VARCHAR(100),
    add_exp1_amt NUMERIC(18,2) DEFAULT 0,
    add_exp2_code INTEGER,
    add_less_exp2 VARCHAR(100),
    add_exp2_amt NUMERIC(18,2) DEFAULT 0,
    bf_gst_amt NUMERIC(18,2) DEFAULT 0,
    igst_code INTEGER, igst_perc NUMERIC(18,2) DEFAULT 0, igst_amt NUMERIC(18,2) DEFAULT 0,
    cgst_code INTEGER, cgst_perc NUMERIC(18,2) DEFAULT 0, cgst_amt NUMERIC(18,2) DEFAULT 0,
    sgst_code INTEGER, sgst_perc NUMERIC(18,2) DEFAULT 0, sgst_amt NUMERIC(18,2) DEFAULT 0,
    rnd_off NUMERIC(18,2) DEFAULT 0,
    net_total NUMERIC(18,2) DEFAULT 0,
    rnd_code INTEGER,
    status VARCHAR(50) DEFAULT 'Pending',
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE del_chall_mast ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS del_chall_child (
    ref_no SERIAL PRIMARY KEY,
    del_ref_no INTEGER REFERENCES del_chall_mast(del_ref_no) ON DELETE CASCADE,
    prcode INTEGER REFERENCES product(ref_no),
    grcode INTEGER REFERENCES product_group(ref_no),
    qty NUMERIC(18,2) DEFAULT 0,
    rate NUMERIC(18,2) DEFAULT 0,
    disc_perc NUMERIC(18,2) DEFAULT 0, disc_amt NUMERIC(18,2) DEFAULT 0,
    total NUMERIC(18,2) DEFAULT 0,
    igst_perc NUMERIC(18,2) DEFAULT 0, igst_amnt NUMERIC(18,2) DEFAULT 0,
    cgst_perc NUMERIC(18,2) DEFAULT 0, cgst_amnt NUMERIC(18,2) DEFAULT 0,
    sgst_perc NUMERIC(18,2) DEFAULT 0, sgst_amnt NUMERIC(18,2) DEFAULT 0,
    net_tot NUMERIC(18,2) DEFAULT 0,
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE del_chall_child ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS wholesale_mast (
    whl_ref_no SERIAL PRIMARY KEY,
    del_ref_no INTEGER REFERENCES del_chall_mast(del_ref_no),
    rec_no INTEGER,
    reg_code INTEGER DEFAULT 50,
    tax_model VARCHAR(50),
    cr_code INTEGER REFERENCES ledger(ledg_code),
    dr_code INTEGER REFERENCES ledger(ledg_code),
    dc_no VARCHAR(50),
    order_no VARCHAR(50),
    rev_chrg VARCHAR(10) DEFAULT 'No',
    inv_type VARCHAR(50),
    eway_bill_no VARCHAR(50),
    ewb_dt TIMESTAMPTZ,
    transport VARCHAR(100),
    trans_id VARCHAR(50), trans_name VARCHAR(100),
    trans_mode VARCHAR(50), distance VARCHAR(50),
    trans_doc_no VARCHAR(50), trans_doc_dt TIMESTAMPTZ,
    veh_no VARCHAR(50), veh_type VARCHAR(50),
    bill_char VARCHAR(10),
    bill_ref_no VARCHAR(50),
    bill_date TIMESTAMPTZ,
    tot_qty NUMERIC(18,2) DEFAULT 0,
    grd_tot NUMERIC(18,2) DEFAULT 0,
    dr_narr VARCHAR(500), cr_narr VARCHAR(500),
    add_less_exp1 VARCHAR(100),
    add_exp1_amt NUMERIC(18,2) DEFAULT 0,
    add_exp2_code INTEGER,
    add_less_exp2 VARCHAR(100),
    add_exp2_amt NUMERIC(18,2) DEFAULT 0,
    bf_gst_amt NUMERIC(18,2) DEFAULT 0,
    igst_code INTEGER, igst_perc NUMERIC(18,2) DEFAULT 0, igst_amt NUMERIC(18,2) DEFAULT 0,
    cgst_code INTEGER, cgst_perc NUMERIC(18,2) DEFAULT 0, cgst_amt NUMERIC(18,2) DEFAULT 0,
    sgst_code INTEGER, sgst_perc NUMERIC(18,2) DEFAULT 0, sgst_amt NUMERIC(18,2) DEFAULT 0,
    rnd_off NUMERIC(18,2) DEFAULT 0,
    net_total NUMERIC(18,2) DEFAULT 0,
    rnd_code INTEGER,
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE wholesale_mast ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS wholesale_child (
    ref_no SERIAL PRIMARY KEY,
    whl_ref_no INTEGER REFERENCES wholesale_mast(whl_ref_no) ON DELETE CASCADE,
    prcode INTEGER REFERENCES product(ref_no),
    grcode INTEGER REFERENCES product_group(ref_no),
    qty NUMERIC(18,2) DEFAULT 0,
    rate NUMERIC(18,2) DEFAULT 0,
    disc_perc NUMERIC(18,2) DEFAULT 0, disc_amt NUMERIC(18,2) DEFAULT 0,
    total NUMERIC(18,2) DEFAULT 0,
    igst_perc NUMERIC(18,2) DEFAULT 0, igst_amnt NUMERIC(18,2) DEFAULT 0,
    cgst_perc NUMERIC(18,2) DEFAULT 0, cgst_amnt NUMERIC(18,2) DEFAULT 0,
    sgst_perc NUMERIC(18,2) DEFAULT 0, sgst_amnt NUMERIC(18,2) DEFAULT 0,
    net_tot NUMERIC(18,2) DEFAULT 0,
    dr_code INTEGER,
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE wholesale_child ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS wholesale_ret_mast (
    whr_ref_no SERIAL PRIMARY KEY,
    del_ref_no INTEGER,
    rec_no INTEGER,
    reg_code INTEGER DEFAULT 50,
    tax_model VARCHAR(50),
    cr_code INTEGER REFERENCES ledger(ledg_code),
    dr_code INTEGER REFERENCES ledger(ledg_code),
    dc_no VARCHAR(50),
    order_no VARCHAR(50),
    rev_chrg VARCHAR(10) DEFAULT 'No',
    inv_type VARCHAR(50),
    eway_bill_no VARCHAR(50),
    ewb_dt TIMESTAMPTZ,
    transport VARCHAR(100),
    trans_id VARCHAR(50), trans_name VARCHAR(100),
    trans_mode VARCHAR(50), distance VARCHAR(50),
    trans_doc_no VARCHAR(50), trans_doc_dt TIMESTAMPTZ,
    veh_no VARCHAR(50), veh_type VARCHAR(50),
    bill_char VARCHAR(10),
    bill_ref_no VARCHAR(50),
    bill_date TIMESTAMPTZ,
    tot_qty NUMERIC(18,2) DEFAULT 0,
    grd_tot NUMERIC(18,2) DEFAULT 0,
    dr_narr VARCHAR(500), cr_narr VARCHAR(500),
    add_less_exp1 VARCHAR(100),
    add_exp1_amt NUMERIC(18,2) DEFAULT 0,
    add_exp2_code INTEGER,
    add_less_exp2 VARCHAR(100),
    add_exp2_amt NUMERIC(18,2) DEFAULT 0,
    bf_gst_amt NUMERIC(18,2) DEFAULT 0,
    igst_code INTEGER, igst_perc NUMERIC(18,2) DEFAULT 0, igst_amt NUMERIC(18,2) DEFAULT 0,
    cgst_code INTEGER, cgst_perc NUMERIC(18,2) DEFAULT 0, cgst_amt NUMERIC(18,2) DEFAULT 0,
    sgst_code INTEGER, sgst_perc NUMERIC(18,2) DEFAULT 0, sgst_amt NUMERIC(18,2) DEFAULT 0,
    rnd_off NUMERIC(18,2) DEFAULT 0,
    net_total NUMERIC(18,2) DEFAULT 0,
    rnd_code INTEGER,
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE wholesale_ret_mast ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS wholesale_ret_child (
    ref_no SERIAL PRIMARY KEY,
    whr_ref_no INTEGER REFERENCES wholesale_ret_mast(whr_ref_no) ON DELETE CASCADE,
    prcode INTEGER REFERENCES product(ref_no),
    grcode INTEGER REFERENCES product_group(ref_no),
    qty NUMERIC(18,2) DEFAULT 0,
    rate NUMERIC(18,2) DEFAULT 0,
    disc_perc NUMERIC(18,2) DEFAULT 0, disc_amt NUMERIC(18,2) DEFAULT 0,
    total NUMERIC(18,2) DEFAULT 0,
    igst_perc NUMERIC(18,2) DEFAULT 0, igst_amnt NUMERIC(18,2) DEFAULT 0,
    cgst_perc NUMERIC(18,2) DEFAULT 0, cgst_amnt NUMERIC(18,2) DEFAULT 0,
    sgst_perc NUMERIC(18,2) DEFAULT 0, sgst_amnt NUMERIC(18,2) DEFAULT 0,
    net_tot NUMERIC(18,2) DEFAULT 0,
    dr_code INTEGER,
    frm_code INTEGER REFERENCES company(frm_code),
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE wholesale_ret_child ENABLE ROW LEVEL SECURITY;
