-- 011_rls_policies.sql
-- Disables RLS on application tables to allow custom application authentication & REST API access

ALTER TABLE company DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_setting DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_permission DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_log_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE session DISABLE ROW LEVEL SECURITY;
ALTER TABLE amount_setup DISABLE ROW LEVEL SECURITY;

ALTER TABLE group_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE sub_group DISABLE ROW LEVEL SECURITY;
ALTER TABLE ledger DISABLE ROW LEVEL SECURITY;
ALTER TABLE ledg_opp_balance DISABLE ROW LEVEL SECURITY;
ALTER TABLE receipt_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE receipt_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE journal_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE journal_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE contra_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE contra_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE credit_note_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE credit_note_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE debit_note_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE debit_note_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE bill_adjustment DISABLE ROW LEVEL SECURITY;

ALTER TABLE units_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_group DISABLE ROW LEVEL SECURITY;
ALTER TABLE product DISABLE ROW LEVEL SECURITY;
ALTER TABLE colour_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE design DISABLE ROW LEVEL SECURITY;
ALTER TABLE warp_type DISABLE ROW LEVEL SECURITY;
ALTER TABLE weft_type DISABLE ROW LEVEL SECURITY;
ALTER TABLE warp_sheet DISABLE ROW LEVEL SECURITY;
ALTER TABLE bar_temp DISABLE ROW LEVEL SECURITY;
ALTER TABLE prod_opp_bal DISABLE ROW LEVEL SECURITY;
ALTER TABLE yarn_opp DISABLE ROW LEVEL SECURITY;
ALTER TABLE stock_journal DISABLE ROW LEVEL SECURITY;

ALTER TABLE tax_reg DISABLE ROW LEVEL SECURITY;
ALTER TABLE tax_setup DISABLE ROW LEVEL SECURITY;
ALTER TABLE prod_tax_setup DISABLE ROW LEVEL SECURITY;
ALTER TABLE sac_tax_setup DISABLE ROW LEVEL SECURITY;
ALTER TABLE pur_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE pur_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE pur_ret_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE pur_ret_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE inward DISABLE ROW LEVEL SECURITY;

ALTER TABLE estimate_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE estimate_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE retail_sale_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE retail_sale_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE retail_sale_ret_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE retail_sale_ret_child DISABLE ROW LEVEL SECURITY;

ALTER TABLE del_chall_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE del_chall_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE wholesale_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE wholesale_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE wholesale_ret_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE wholesale_ret_child DISABLE ROW LEVEL SECURITY;

ALTER TABLE lot_info DISABLE ROW LEVEL SECURITY;
ALTER TABLE twist_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE twist_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE twist_recd_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE twist_recd_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE dyeing_issue_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE dyeing_issue_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE dyeing_recd_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE dyeing_recd_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE loom DISABLE ROW LEVEL SECURITY;
ALTER TABLE weav_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE weaving_trans DISABLE ROW LEVEL SECURITY;
ALTER TABLE weaver_pay_setting DISABLE ROW LEVEL SECURITY;
ALTER TABLE weav_pay_confirm DISABLE ROW LEVEL SECURITY;
ALTER TABLE cost_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE cost_child DISABLE ROW LEVEL SECURITY;

ALTER TABLE itc_mast DISABLE ROW LEVEL SECURITY;
ALTER TABLE itc_child DISABLE ROW LEVEL SECURITY;
ALTER TABLE ps_stock_master DISABLE ROW LEVEL SECURITY;
ALTER TABLE ps_stock_child DISABLE ROW LEVEL SECURITY;

-- Ensure default admin user exists
INSERT INTO admin (user_name, user_password, user_type, user_status) 
VALUES ('admin', 'admin123', 'Administrator', 'Active')
ON CONFLICT (user_name) DO UPDATE 
SET user_password = 'admin123', user_status = 'Active';
